import pandas as pd
import argparse
from can_parser import CANDatabase, convert_name_convention


def generate_can_code(
    db_file, naming_convention, output_file, generate_min_max, generate_meta
):
    df = pd.read_csv(db_file)
    # Ensure data has necessary columns and clean the data
    df = df.dropna(
        subset=["Message Name", "Start Bit", "Size (bits)", "Factor", "Offset"]
    )
    df = df.drop(df.columns[df.columns.str.contains("unnamed", case=False)], axis=1)

    # replace any na values with ""
    # this is because the parser code expects empty strings
    df = df.fillna("")

    # Combine dataframes named columns with the rest of the values
    lists = [list(df.columns), *df.values.tolist()]
    db = CANDatabase(lists)

    buses = db.get_buses()
    messages = db.get_messages().values()

    with open(output_file, "w") as f:
        file_w_str = ""

        file_w_str += "#pragma once\n\n"

        file_w_str += (
            "// This file was autogenerated by the CAN parser. Do not edit.\n\n"
        )

        # Necessary includes
        file_w_str += "#include <nfr_can/CAN_interface.hpp>\n\n"
        if generate_min_max:
            file_w_str += "#include <map>\n\n"


        global_namespace = "dbc"

        # Provide namespace wrapper
        file_w_str += f"namespace {global_namespace} {{ \n\n"

        # create the can buses:
        for bus in buses:
            bus_name = bus.get_cpp_bus_name(naming_convention)
            # driver_name = convert_name_convention(f"{bus_name}_driver", naming_convention)
            # file_w_str += f"static ICAN {driver_name};\n"
            file_w_str += f"static CAN_Bus {bus_name};\n"

        file_w_str += "\n\n"

        for message in messages:
            # create a message namespace
            message_namespace_name = convert_name_convention(
                message.message_name, naming_convention
            )
            file_w_str += f"namespace {message_namespace_name} {{ \n\n"
            # add signal code
            signals = message.get_signals()
            for signal in signals:
                signal_str = signal.as_cpp_code(naming_convention)
                file_w_str += f"{signal_str}\n"

            bus = buses[0].get_cpp_bus_name(naming_convention)
            message_override_name = convert_name_convention(
                "message", naming_convention
            )
            can_msg_str = message.as_cpp_receive_code(
                bus, naming_convention, message_override_name
            )

            file_w_str += f"{can_msg_str}\n\n"

            # now add some min & max values, if they exist for each signal
            if generate_min_max:
                for signal in signals:
                    signal_str = signal.as_cpp_min_max_code(naming_convention)
                    if signal_str is None or signal_str == "":
                        continue
                    file_w_str += f"{signal_str}\n"
                file_w_str += "\n"

            file_w_str += f"}}; // namespace {message_namespace_name}\n\n"

        if generate_meta:
            # generate a vector that maps from message id to message name
            # uint32_t to const char *

            # namespace meta
            map_name = convert_name_convention("message_id_to_name", naming_convention)  # "message_id_to_name"

            file_w_str += f"namespace meta {{ \n\n"
            file_w_str += f"static const std::map<uint32_t, const char*> {map_name} = {{\n"
            for message in messages:
                file_w_str += (
                    f'    {{ {message.message_id}, "{message.message_name}" }},\n'
                )
            file_w_str += f"}};\n\n"

            # now map from std::pair<uint32_t, uint8_t> where the first is the message id, and the second is the signal index
            # to the signal name
            map_name = convert_name_convention("signal_id_to_name", naming_convention)  # "signal_id_to_name"

            file_w_str += f"static const std::map<std::pair<uint32_t, uint8_t>, const char*> {map_name} = {{\n"
            for message in messages:
                signal_num = 0
                for signal in message.get_signals():
                    file_w_str += (
                        f'    {{ {{ {message.message_id}, {signal_num} }}, "{signal.signal_name}" }},\n'
                    )
                    signal_num += 1
                    
            file_w_str += f"}};\n\n"

            file_w_str += f"}}; // namespace meta\n\n"

        file_w_str += f"}}; // namespace {global_namespace}"
        f.write(file_w_str)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "dbc_file", help="DBC file that is read and utilized to generate the cpp code."
    )
    parser.add_argument(
        "-o",
        "--output_file",
        help="Provide a designated output file. Default is can_dbc.hpp",
        default="can_dbc.hpp",
    )
    parser.add_argument(
        "-c",
        "--convention",
        help="Provide a naming convention. Default is PascalCase",
        default="PascalCase",
    )
    parser.add_argument(
        "--min-max",
        action="store_true",
        help="Generate min and max values for each signal",
    )
    parser.add_argument(
        "--meta",
        action="store_true",
        help="Generate meta data for each signal and message",
    )

    args = parser.parse_args()
    generate_can_code(
        args.dbc_file, 
        args.convention, 
        args.output_file, 
        args.min_max, 
        args.meta
    )


if __name__ == "__main__":
    main()
