import pandas as pd
import argparse
from can_parser import CANDatabase, convert_name_convention

def generate_can_code(db_file, naming_convention, output_file):
    df = pd.read_csv(db_file)
    # Ensure data has necessary columns and clean the data
    df = df.dropna(subset=['Message Name', 'Start Bit', 'Size (bits)', 'Factor', 'Offset'])
    df = df.drop(df.columns[df.columns.str.contains('unnamed', case = False)], axis = 1)

    # replace any na values with ""
    # this is because the parser code expects empty strings
    df = df.fillna("")

    # Combine dataframes named columns with the rest of the values
    lists = [list(df.columns), *df.values.tolist()]
    db = CANDatabase(lists)

    buses = db.get_buses()
    messages = db.get_messages().values()
    
    with open(output_file, "w") as f:
        file_w_str = ""

        file_w_str += "#pragma once\n\n"

        file_w_str += "// This file was autogenerated by the CAN parser. Do not edit.\n\n"

        # Necessary includes
        file_w_str += "#include <nfr_can/CAN_interface.hpp>\n\n"
        global_namespace = "dbc"

        # Provide namespace wrapper
        file_w_str += f"namespace {global_namespace} {{ \n\n"

        # create the can buses:
        for bus in buses:
            bus_name = bus.get_cpp_bus_name(naming_convention)
            # driver_name = convert_name_convention(f"{bus_name}_driver", naming_convention)
            # file_w_str += f"static ICAN {driver_name};\n"
            file_w_str += f"static CAN_Bus {bus_name};\n"
        
        file_w_str += "\n\n"

        for message in messages:
            # create a message namespace
            message_namespace_name =  convert_name_convention(message.message_name, naming_convention)
            file_w_str += f"namespace {message_namespace_name} {{ \n\n"
            # add signal code
            signals = message.get_signals()
            for signal in signals:
                signal_str = signal.as_cpp_code(naming_convention)
                file_w_str += f"{signal_str}\n"

            bus = buses[0].get_cpp_bus_name(naming_convention)
            message_override_name = convert_name_convention("message", naming_convention)
            can_msg_str = message.as_cpp_receive_code(bus, naming_convention, message_override_name)
            
            file_w_str += f"{can_msg_str}\n\n"

            # now add some min & max values, if they exist for each signal
            for signal in signals:
                signal_str = signal.as_cpp_min_max_code(naming_convention)
                if signal_str is None or signal_str == "":
                    continue
                file_w_str += f"{signal_str}\n"
            
            file_w_str += "\n"
            file_w_str += f"}}; // namespace {message_namespace_name}\n\n"

        file_w_str += f"}}; // namespace {global_namespace}"
        f.write(file_w_str)
        

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("dbc_file", help="DBC file that is read and utilized to generate the cpp code.")
    parser.add_argument("-o", "--output_file", help = "Provide a designated output file. Default is can_dbc.hpp", default="can_dbc.hpp")
    parser.add_argument("-c", "--convention", help="Provide a naming convention. Default is PascalCase", default="PascalCase")
    args = parser.parse_args()

    dbc_file = args.dbc_file
    output_file = args.output_file
    naming_convention = args.convention
    generate_can_code(dbc_file, naming_convention, output_file)


if __name__ == "__main__":
    main()